# SPDX-License-Identifier: GPL-2.0

userprogs += poc_vuln_printk_leak
userprogs += poc_vuln_stack_leak
userprogs += poc_vuln_race_device
userprogs += poc_vuln_int_ovf
userprogs += poc_vuln_shmem

always-y := $(userprogs)

userccflags += -Wno-declaration-after-statement
